---
# Minimal MongoDB ReplicaSet Example
# Production-ready but simplified configuration for moderate workloads
# Features: 3-member replica set, 10Gi storage, SCRAM-SHA-256 authentication

apiVersion: mongodb.keiailab.com/v1alpha1
kind: MongoDB
metadata:
  name: my-mongodb
  namespace: database
spec:
  # Number of replica set members (3 for high availability)
  members: 3

  # MongoDB version
  version:
    version: "8.2"

  # ReplicaSet name (used for internal cluster identification)
  replicaSetName: rs0

  # Storage configuration
  storage:
    # Update to match your cluster's storage class
    storageClassName: standard
    size: 10Gi
    dataDirPath: /data/db

  # Resource requirements (minimal for testing/development)
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "2Gi"

  # Authentication configuration
  auth:
    mechanism: SCRAM-SHA-256
    # Reference to admin credentials secret (create before deployment)
    adminCredentialsSecretRef:
      name: mongodb-admin-credentials
    # Optional: Create application users
    users:
      - name: appuser
        db: admin
        passwordSecretRef:
          name: mongodb-app-credentials
          key: password
        roles:
          - name: readWrite
            db: myapp

  # Service configuration (ClusterIP for internal access)
  service:
    type: ClusterIP

  # Pod configuration
  pod:
    securityContext:
      fsGroup: 999
      runAsUser: 999
      runAsNonRoot: true

---
# Admin credentials Secret
# Create this secret before deploying the MongoDB resource
# IMPORTANT: Use strong passwords in production!
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-admin-credentials
  namespace: database
type: Opaque
stringData:
  username: admin
  # Replace with strong password in production
  password: "change-me-in-production"

---
# Application user credentials Secret
# Create this secret before deploying the MongoDB resource
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-app-credentials
  namespace: database
type: Opaque
stringData:
  # Replace with strong password in production
  password: "app-password-change-me"

---
# Namespace (optional - create if namespace doesn't exist)
apiVersion: v1
kind: Namespace
metadata:
  name: database
