coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: false
        base: auto
    patch:
      default:
        target: auto
        threshold: 1%
        informational: false
        base: auto

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false

ignore:
  - "**/*_test.go"
  - "**/zz_*.go"
  - "**/*.pb.go"
  - "third_party/**"
  - "vendor/**"
